package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      bz.rxla.audioplayer.AudioplayerPlugin.registerWith(shimPluginRegistry.registrarFor("bz.rxla.audioplayer.AudioplayerPlugin"));
    flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin());
      com.example.systemshortcuts.SystemShortcutsPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.systemshortcuts.SystemShortcutsPlugin"));
      com.example.volume.VolumePlugin.registerWith(shimPluginRegistry.registrarFor("com.example.volume.VolumePlugin"));
  }
}
